version: '3'
services:
  student-management-system:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


